version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379